version: "3.5"

services:
  crebito-api-1:
    hostname: crebito-api-1
    build: ./app
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=db:3306
      - DB_INITIAL_POOL_SIZE=13
      - DB_MAX_POOL_SIZE=13
      - spring
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "400MB"

  crebito-api-2:
    hostname: crebito-api-2
    build: ./app
    ports:
      - "8082:8080"
    environment:
      - DB_HOST=db:3306
      - DB_INITIAL_POOL_SIZE=13
      - DB_MAX_POOL_SIZE=13
      - spring
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "400MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - crebito-api-1
      - crebito-api-2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"
  db:
    image: mariadb:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: rinha
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1